// Daftar pertanyaan QOTD (Question of the Day) - tema gaming/Game Verse
// Tambahin/edit bebas sesuai selera komunitas kamu

module.exports = [
    "Game apa yang paling lama lu mainin sampe sekarang, dan kenapa gak bosen-bosen?",
    "Kalo lu bisa jadi 1 karakter game buat sehari, lu pilih siapa?",
    "Momen paling epic/clutch yang pernah lu lakuin di game apa?",
    "Game apa yang menurut lu overrated banget padahal banyak yang suka?",
    "Setup gaming impian lu kayak gimana? (device, chair, meja, dll)",
    "Rank/level tertinggi yang pernah lu capai di game apa, susah ga cara dapetinnya?",
    "Kalo disuruh milih 1 game buat dimainin seumur hidup doang, lu pilih apa?",
    "Tim/squad paling absurd yang pernah lu temuin pas mabar cerita dong!",
    "Item/skin game paling worth it yang pernah lu beli apa?",
    "Genre game apa yang dulu lu benci tapi sekarang malah jadi favorit?",
    "First game yang lu maenin seumur hidup apa, masih inget ga rasanya?",
    "Kalo lu bisa gabungin 2 game jadi 1, lu gabungin apa aja?",
    "Boss/musuh paling nyusahin yang pernah lu lawan di game apa?",
    "Kebiasaan aneh apa yang lu lakuin pas lagi push rank/tier?",
    "NPC atau karakter game yang menurut lu paling relate sama hidup lu siapa?",
    "Kalo lu jadi game developer sehari, mau bikin fitur apa di game favorit lu?",
    "Momen paling bikin emosi pas mabar sama temen apa?",
    "Game yang lu pengen banget coba tapi belum sempet apa?",
    "Kalo device gaming lu cuma boleh 1, HP, PC, atau konsol yang lu pilih?",
    "Julukan/nickname in-game paling absurd yang pernah lu pake apa?",
    "Server/guild/clan paling solid yang pernah lu ikutin ceritain dong!",
    "Skill di real life yang menurut lu kepake banget gara-gara sering main game?",
    "Update/patch game yang paling bikin lu excited belakangan ini apa?",
    "Kalo lu bisa ngobrol sama karakter game favorit lu, mau nanya apa?",
    "Achievment/pencapaian in-game yang paling lu banggain apa?",
];